services:
    david63.subforumposts.listener:
        class: david63\subforumposts\event\listener
        arguments:
            - '@dbal.conn'
            - '%tables%'
        tags:
            - { name: event.listener }
